INSERT INTO `trivniac`.`questions` (category, question, option_1, option_2, option_3, option_4, answer) VALUES
-- History Questions
('History', 'Which year did the Roman Republic become the Roman Empire under Augustus?', '27 BC', '14 AD', '476 AD', '509 BC', 1),
('History', 'During which year was the Magna Carta signed?', '1215', '1066', '1453', '1492', 1),
('History', 'When did the Battle of Hastings take place?', '1066', '1215', '1000', '1250', 1),
('History', 'In which year was the Declaration of Independence signed?', '1776', '1787', '1775', '1774', 1),
('History', 'In which year was the fall of Constantinople?', '1453', '1492', '1454', '1500', 1),
('History', 'Which year saw the French Revolution begin?', '1789', '1799', '1815', '1776', 1),
('History', 'Which year was the first successful English colony at Jamestown founded?', '1607', '1620', '1492', '1588', 1),
('History', 'In which year did Martin Luther nail his 95 Theses?', '1517', '1534', '1492', '1521', 1),
('History', 'In which year did the Russian Revolution begin?', '1917', '1905', '1922', '1933', 1),
('History', 'In which year did the Hundred Years\' War begin?', '1337', '1415', '1066', '1204', 1),
('History', 'In which year did the Glorious Revolution occur in England?', '1688', '1642', '1689', '1660', 1),
('History', 'In which year did the United Nations officially form?', '1945', '1919', '1942', '1939', 1),
('History', 'In which year did the Berlin Wall fall?', '1989', '1991', '1987', '1979', 1),
('History', 'Who was the first President of the United States?', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'John Adams', 2),
('History', 'Who famously said \"I came, I saw, I conquered\"?', 'Nero', 'Julius Caesar', 'Alexander the Great', 'Genghis Khan', 2),
('History', 'Who was the first Tudor king of England?', 'Henry VIII', 'Henry VII', 'Edward VI', 'Richard III', 2),
('History', 'Who led the Soviet Union during World War II?', 'Vladimir Lenin', 'Joseph Stalin', 'Nikita Khrushchev', 'Leon Trotsky', 2),
('History', 'Which Mongol ruler created the largest contiguous empire in history?', 'Kublai Khan', 'Genghis Khan', 'Tamerlane', 'Batu Khan', 2),
('History', 'Which queen sponsored Columbus\'s voyage to the New World?', 'Queen Elizabeth I', 'Queen Isabella I', 'Catherine the Great', 'Queen Anne', 2),
('History', 'Who was known as the Sun King?', 'Philip II of Spain', 'Louis XIV of France', 'Henry IV of France', 'Charles V', 2),
('History', 'Which leader is associated with the unification of Germany in 1871?', 'Friedrich Ebert', 'Otto von Bismarck', 'Wilhelm II', 'Helmut Kohl', 2),
('History', 'Who was the British Prime Minister during most of World War II?', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Stanley Baldwin', 2),
('History', 'Who led India to independence through nonviolent protest?', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Muhammad Ali Jinnah', 'Subhas Chandra Bose', 2),
('History', 'Who was the principal author of the Declaration of Independence?', 'John Adams', 'Thomas Jefferson', 'Benjamin Franklin', 'James Madison', 2),
('History', 'Which pharaoh built the Great Pyramid of Giza?', 'Tutankhamun', 'Khufu', 'Ramesses II', 'Sneferu', 2),
('History', 'Who launched the Protestant Reformation in 16th-century Europe?', 'John Calvin', 'Martin Luther', 'Ulrich Zwingli', 'John Knox', 2),
('History', 'Which war was known as \"The Great War\" before World War II?', 'World War II', 'The Napoleonic Wars', 'World War I', 'The Seven Years\' War', 3),
('History', 'In which conflict did the Battle of Gettysburg occur?', 'War of 1812', 'Spanish-American War', 'American Civil War', 'Revolutionary War', 3),
('History', 'Which war ended with the Treaty of Versailles?', 'Franco-Prussian War', 'Russian Civil War', 'World War I', 'World War II', 3),
('History', 'Which war was triggered by the assassination of Archduke Franz Ferdinand?', 'World War II', 'Balkan Wars', 'World War I', 'Crimean War', 3),
('History', 'During which war did the D-Day landings occur?', 'World War I', 'Vietnam War', 'World War II', 'Korean War', 3),
('History', 'Which war saw the first use of tanks in battle?', 'Boer War', 'Russian Civil War', 'World War I', 'World War II', 3),
('History', 'In which war was the Battle of Midway fought?', 'Korean War', 'World War I', 'World War II', 'Gulf War', 3),
('History', 'In which war was the Battle of Waterloo fought?', 'Seven Years\' War', 'World War I', 'Napoleonic Wars', 'War of the Austrian Succession', 3),
('History', 'Which war began in 1950 on the Korean peninsula?', 'World War II', 'Chinese Civil War', 'Korean War', 'Vietnam War', 3),
('History', 'In which war was the Battle of Thermopylae fought?', 'Peloponnesian War', 'Punic Wars', 'Greco-Persian Wars', 'Macedonian Wars', 3),
('History', 'Which war was also called the Great Patriotic War in Russia?', 'Russo-Japanese War', 'World War I', 'World War II', 'Russian Civil War', 3),
('History', 'In which war did Florence Nightingale pioneer modern nursing?', 'World War I', 'American Civil War', 'Crimean War', 'Boer War', 3),
('History', 'Which city served as the capital of the Aztec Empire?', 'Machu Picchu', 'Teotihuacan', 'Cuzco', 'Tenochtitlan', 4),
('History', 'Which city was known as Byzantium before becoming Constantinople?', 'Athens', 'Alexandria', 'Antioch', 'Istanbul', 4),
('History', 'In which ancient city did the Hanging Gardens supposedly exist?', 'Uruk', 'Nineveh', 'Rome', 'Babylon', 4),
('History', 'What was the name of the eastern half of the Roman Empire after 395 AD?', 'Hellenic Empire', 'Rus Empire', 'Persian Empire', 'Byzantine Empire', 4),
('History', 'Which city was famously led by Pericles during its Golden Age?', 'Sparta', 'Corinth', 'Thebes', 'Athens', 4),
('History', 'Which city was historically known as Edo?', 'Kyoto', 'Busan', 'Shanghai', 'Tokyo', 4),
('History', 'What was the largest city in the world during the Tang dynasty?', 'Cairo', 'Constantinople', 'Baghdad', 'Chang\'an', 4),
('History', 'Which major city was known as the \"City of the World\'s Desire\"?', 'Vienna', 'London', 'Paris', 'Istanbul', 4),
('History', 'Which city is considered by many to be the oldest continuously inhabited city in the world?', 'Byblos', 'Jericho', 'Aleppo', 'Damascus', 4),
('History', 'Which city was the heart of the Renaissance in Italy?', 'Rome', 'Venice', 'Milan', 'Florence', 4),
('History', 'Which city was sacked by the Visigoths in 410 AD?', 'Constantinople', 'Milan', 'Ravenna', 'Rome', 4),
('History', 'In which city was the Treaty of Tordesillas signed in 1494?', 'Madrid', 'Lisbon', 'Seville', 'Tordesillas', 4),



-- Sports Questions
('Sports', 'Which country has won the most FIFA World Cup titles?', 'Brazil', 'Germany', 'Italy', 'Argentina', 1),
('Sports', 'Which MLB team has won the most World Series titles?', 'New York Yankees', 'St. Louis Cardinals', 'Boston Red Sox', 'San Francisco Giants', 1),
('Sports', 'Which NBA team has the most championships?', 'Boston Celtics', 'Los Angeles Lakers', 'Golden State Warriors', 'Chicago Bulls', 1),
('Sports', 'Who holds the record for most goals in a calendar year in professional soccer?', 'Lionel Messi', 'Cristiano Ronaldo', 'Pelé', 'Gerd Müller', 1),
('Sports', 'Which tennis Grand Slam is played on clay courts?', 'French Open', 'Australian Open', 'Wimbledon', 'US Open', 1),
('Sports', 'Which NFL team has won the most Super Bowls?', 'Pittsburgh Steelers', 'New England Patriots', 'Dallas Cowboys', 'Green Bay Packers', 1),
('Sports', 'Which golf major is held annually at Augusta National Golf Club?', 'The Masters', 'US Open', 'The Open Championship', 'PGA Championship', 1),
('Sports', 'Which country is associated with the sport of sumo wrestling?', 'Japan', 'China', 'Mongolia', 'South Korea', 1),
('Sports', 'Which team has won the most English Premier League titles?', 'Manchester United', 'Liverpool', 'Arsenal', 'Chelsea', 1),
('Sports', 'Which sport was Michael Phelps a champion in?', 'Swimming', 'Track & Field', 'Diving', 'Gymnastics', 1),
('Sports', 'Which driver has the most Formula 1 World Championships in history?', 'Michael Schumacher', 'Lewis Hamilton', 'Ayrton Senna', 'Juan Manuel Fangio', 1),
('Sports', 'Who leads the men’s singles Grand Slam title count as of 2023?', 'Novak Djokovic', 'Rafael Nadal', 'Roger Federer', 'Pete Sampras', 1),
('Sports', 'Which NHL team has won the most Stanley Cup championships?', 'Montreal Canadiens', 'Toronto Maple Leafs', 'Detroit Red Wings', 'Boston Bruins', 1),
('Sports', 'Which soccer legend is nicknamed \"O Rei\" (The King)?', 'Diego Maradona', 'Pelé', 'Ronaldinho', 'Zinedine Zidane', 2),
('Sports', 'Which boxer was known as \"The Greatest\" and \"The People\'s Champion\"?', 'Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather Jr.', 'George Foreman', 2),
('Sports', 'Which NFL quarterback has the most Super Bowl rings?', 'Joe Montana', 'Tom Brady', 'Peyton Manning', 'Terry Bradshaw', 2),
('Sports', 'Which female tennis player has won the most Grand Slam singles titles in the Open Era?', 'Martina Navratilova', 'Serena Williams', 'Steffi Graf', 'Margaret Court', 2),
('Sports', 'Which American swimmer earned eight gold medals in the 2008 Beijing Olympics?', 'Ryan Lochte', 'Michael Phelps', 'Ian Thorpe', 'Caeleb Dressel', 2),
('Sports', 'Which soccer team is famous for its \"tiki-taka\" style of play?', 'Real Madrid', 'FC Barcelona', 'Bayern Munich', 'Manchester City', 2),
('Sports', 'Which MLB player holds the single-season home run record (73)?', 'Hank Aaron', 'Barry Bonds', 'Mark McGwire', 'Sammy Sosa', 2),
('Sports', 'Which basketball star was famously nicknamed \"The Black Mamba\"?', 'LeBron James', 'Kobe Bryant', 'Michael Jordan', 'Allen Iverson', 2),
('Sports', 'Which racer holds the record for the most MotoGP/500cc World Championships?', 'Casey Stoner', 'Valentino Rossi', 'Marc Marquez', 'Mick Doohan', 2),
('Sports', 'Which women\'s national soccer team has won the most FIFA Women\'s World Cup titles?', 'Germany', 'United States', 'Japan', 'Norway', 2),
('Sports', 'Which country has hosted the Summer Olympics the most times?', 'Greece', 'United States', 'United Kingdom', 'Japan', 2),
('Sports', 'Which tennis player famously shouted \"You cannot be serious!\" during matches?', 'Jimmy Connors', 'John McEnroe', 'Björn Borg', 'Ilie Năstase', 2),
('Sports', 'Which athlete is widely regarded as the fastest man in history for his 100m world record?', 'Carl Lewis', 'Usain Bolt', 'Maurice Greene', 'Justin Gatlin', 2),
('Sports', 'Which soccer competition is played every four years by national teams around the world?', 'UEFA European Championship', 'Copa América', 'FIFA World Cup', 'AFC Asian Cup', 3),
('Sports', 'Which tournament is the oldest tennis competition in the world?', 'US Open', 'French Open', 'Wimbledon', 'Australian Open', 3),
('Sports', 'Which championship trophy is considered the oldest in North American pro sports?', 'Commissioner\'s Trophy', 'Lombardi Trophy', 'Stanley Cup', 'Larry O\'Brien Trophy', 3),
('Sports', 'Which grand tour cycling race is the most prestigious and oldest among the three?', 'Giro d\'Italia', 'Vuelta a España', 'Tour de France', 'La Flèche Wallonne', 3),
('Sports', 'Which league awards the Vince Lombardi Trophy to its champion?', 'NBA', 'MLB', 'NFL', 'NHL', 3),
('Sports', 'Which cricket tournament, organized by the ICC, is held every four years?', 'T20 World Cup', 'Champions Trophy', 'Cricket World Cup', 'Ashes Series', 3),
('Sports', 'Which basketball competition is considered the top-tier league in Europe?', 'NBA', 'EuroCup', 'EuroLeague', 'Champions League', 3),
('Sports', 'Which city hosts the annual Boston Marathon?', 'New York', 'Chicago', 'Boston', 'Washington D.C.', 3),
('Sports', 'Which race is part of motorsport’s Triple Crown along with Monaco Grand Prix & 24 Hours of Le Mans?', 'Daytona 500', 'Bathurst 1000', 'Indianapolis 500', 'WRC Rally Finland', 3),
('Sports', 'Which annual competition do the top European soccer clubs compete in?', 'Europa League', 'Premier League', 'UEFA Champions League', 'Serie A', 3),
('Sports', 'Which rugby tournament features England, France, Ireland, Italy, Scotland, and Wales?', 'Rugby Championship', 'Tri Nations', 'Six Nations', 'Bledisloe Cup', 3),
('Sports', 'Which multi-sport event is held every four years and is separate from the Olympics?', 'Pan American Games', 'Asian Games', 'Commonwealth Games', 'Mediterranean Games', 3),
('Sports', 'Which sport uses the term \"alley-oop\"?', 'Volleyball', 'American Football', 'Soccer', 'Basketball', 4),
('Sports', 'Which sport uses a \"spike\" as a common attacking move?', 'Basketball', 'Tennis', 'Badminton', 'Volleyball', 4),
('Sports', 'Which sport is associated with the term \"hole in one\"?', 'Snooker', 'Cricket', 'Bowling', 'Golf', 4),
('Sports', 'Which sport is associated with the term \"slam dunk\"?', 'Baseball', 'Handball', 'Water Polo', 'Basketball', 4),
('Sports', 'Which sport typically involves the \"Fosbury Flop\" technique?', 'Gymnastics', 'Pole Vault', 'Diving', 'High Jump', 4),
('Sports', 'Which sport restarts play with a \"scrum\"?', 'American Football', 'Australian Rules Football', 'Gaelic Football', 'Rugby', 4),
('Sports', 'In which sport might a player bowl a \"googly\"?', 'Baseball', 'Tennis', 'Table Tennis', 'Cricket', 4),
('Sports', 'Which sport includes the use of a \"double play\"?', 'Basketball', 'Cricket', 'Softball', 'Baseball', 4),
('Sports', 'Which sport is known for its \"Grand Prix\" events?', 'Rowing', 'Cycling', 'Speed Skating', 'Formula 1', 4),
('Sports', 'Which sport can feature a \"perfect game\" where no opponent reaches base?', 'Cricket', 'Volleyball', 'Basketball', 'Baseball', 4),
('Sports', 'Which sport uses a \"power play\" to describe a team advantage situation?', 'Basketball', 'Soccer', 'American Football', 'Ice Hockey', 4),
('Sports', 'Which sport has a Triple Crown with the Kentucky Derby, Preakness Stakes, and Belmont Stakes?', 'Motor Racing', 'Golf', 'Baseball', 'Horse Racing', 4),


-- Geography Questions
('Geography', 'Which country has the largest population in the world?', 'China', 'India', 'United States', 'Russia', 1),
('Geography', 'Which country is the largest by land area?', 'Russia', 'Canada', 'United States', 'China', 1),
('Geography', 'What is the longest river in the world?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi', 1),
('Geography', 'Which country is called the Land of the Rising Sun?', 'Japan', 'China', 'Thailand', 'South Korea', 1),
('Geography', 'Which country is home to the city of Timbuktu?', 'Mali', 'Nigeria', 'Sudan', 'Niger', 1),
('Geography', 'Which is the smallest country in the world by area?', 'Vatican City', 'Monaco', 'Nauru', 'Tuvalu', 1),
('Geography', 'On which continent is Mount Kilimanjaro located?', 'Africa', 'Asia', 'South America', 'Europe', 1),
('Geography', 'Which country has a maple leaf on its flag?', 'Canada', 'Australia', 'Austria', 'Denmark', 1),
('Geography', 'Which city is known as the Big Apple?', 'New York City', 'Los Angeles', 'Chicago', 'Boston', 1),
('Geography', 'The city of Copenhagen is located in which country?', 'Denmark', 'Sweden', 'Norway', 'Finland', 1),
('Geography', 'Which desert covers much of northern Africa?', 'Sahara', 'Gobi', 'Kalahari', 'Arabian', 1),
('Geography', 'Which mountain range separates Europe from Asia in Russia?', 'Ural Mountains', 'Caucasus Mountains', 'Alps', 'Carpathians', 1),
('Geography', 'The capital of Greece is which city?', 'Athens', 'Thessaloniki', 'Patras', 'Larissa', 1),
('Geography', 'Which city is the capital of Australia?', 'Sydney', 'Canberra', 'Melbourne', 'Brisbane', 2),
('Geography', 'Which country does the Great Barrier Reef belong to?', 'Fiji', 'Australia', 'Philippines', 'Indonesia', 2),
('Geography', 'Which city is the capital of Japan?', 'Osaka', 'Tokyo', 'Kyoto', 'Nagoya', 2),
('Geography', 'Which European city is famous for the Eiffel Tower?', 'London', 'Paris', 'Rome', 'Berlin', 2),
('Geography', 'Which country is known for its fjords, particularly in the western region?', 'Sweden', 'Norway', 'Iceland', 'Finland', 2),
('Geography', 'Which city is known as the City of Canals and located in Italy?', 'Rome', 'Venice', 'Milan', 'Florence', 2),
('Geography', 'Which country has Brasília as its capital?', 'Argentina', 'Brazil', 'Chile', 'Colombia', 2),
('Geography', 'Which city is the capital of Canada?', 'Toronto', 'Ottawa', 'Montreal', 'Vancouver', 2),
('Geography', 'Which country lies on the Iberian Peninsula alongside Spain?', 'France', 'Portugal', 'Andorra', 'Monaco', 2),
('Geography', 'Which country is located on both Europe and Asia?', 'Bulgaria', 'Turkey', 'Georgia', 'Kazakhstan', 2),
('Geography', 'Which country is home to the historical region of Transylvania?', 'Serbia', 'Romania', 'Hungary', 'Moldova', 2),
('Geography', 'Which African lake is the largest by surface area?', 'Lake Tanganyika', 'Lake Victoria', 'Lake Malawi', 'Lake Chad', 2),
('Geography', 'Which country is home to the ancient site of Machu Picchu?', 'Bolivia', 'Peru', 'Ecuador', 'Chile', 2),
('Geography', 'Which capital city sits on the River Thames?', 'Edinburgh', 'Cardiff', 'London', 'Manchester', 3),
('Geography', 'Which city is the capital of Egypt?', 'Alexandria', 'Giza', 'Cairo', 'Luxor', 3),
('Geography', 'Which large sea is located between Africa and the Arabian Peninsula?', 'Mediterranean Sea', 'Arabian Sea', 'Red Sea', 'Persian Gulf', 3),
('Geography', 'Which ocean is the smallest by total area?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Southern Ocean', 3),
('Geography', 'Which city is the capital of Argentina?', 'Rosario', 'Córdoba', 'Buenos Aires', 'Mendoza', 3),
('Geography', 'Which volcano famously erupted in 79 AD, burying Pompeii?', 'Mount Etna', 'Stromboli', 'Mount Vesuvius', 'Mount Olympus', 3),
('Geography', 'Which US state is the Grand Canyon located in?', 'Nevada', 'Utah', 'Arizona', 'New Mexico', 3),
('Geography', 'Which continent is both a country and a continent?', 'Europe', 'Asia', 'Australia', 'North America', 3),
('Geography', 'Which desert is located primarily in Mongolia and China?', 'Sahara', 'Arabian Desert', 'Gobi Desert', 'Taklamakan', 3),
('Geography', 'Which is the second longest river in the world?', 'Nile', 'Yangtze', 'Amazon', 'Mississippi', 3),
('Geography', 'Which African country has the largest population?', 'Ethiopia', 'South Africa', 'Nigeria', 'Egypt', 3),
('Geography', 'Which mountains form the backbone of Italy?', 'Pyrenees', 'Carpathian Mountains', 'Apennines', 'Alps', 3),
('Geography', 'Which city is the capital of South Korea?', 'Busan', 'Incheon', 'Daegu', 'Seoul', 4),
('Geography', 'Which US state is known as the Aloha State?', 'California', 'Florida', 'Texas', 'Hawaii', 4),
('Geography', 'Which city is the capital of Russia?', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Moscow', 4),
('Geography', 'Which ancient city was known as Constantinople?', 'Ankara', 'Athens', 'Rome', 'Istanbul', 4),
('Geography', 'Which country is the island of Bali a part of?', 'Malaysia', 'Thailand', 'Philippines', 'Indonesia', 4),
('Geography', 'Which country owns Greenland?', 'Iceland', 'United Kingdom', 'Norway', 'Denmark', 4),
('Geography', 'Which US city is famously known as the Windy City?', 'Houston', 'Philadelphia', 'Boston', 'Chicago', 4),
('Geography', 'Which city is the capital of the Netherlands?', 'Rotterdam', 'The Hague', 'Utrecht', 'Amsterdam', 4),
('Geography', 'Which Middle Eastern city is known as the City of Gold?', 'Riyadh', 'Abu Dhabi', 'Manama', 'Dubai', 4),
('Geography', 'Which country is the city of Salzburg located in?', 'Germany', 'Switzerland', 'Czech Republic', 'Austria', 4),
('Geography', 'Which capital city is located near the Temple of the Tooth (Sri Dalada Maligawa)?', 'Kathmandu', 'New Delhi', 'Islamabad', 'Kandy', 4),
('Geography', 'Which southern African country has three capitals (executive, judicial, and legislative)?', 'Zambia', 'Zimbabwe', 'Botswana', 'South Africa', 4),


-- Science Questions
('Science', 'Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Saturn', 1),
('Science', 'Which subatomic particle carries a negative charge?', 'Electron', 'Proton', 'Neutron', 'Positron', 1),
('Science', 'What is the chemical symbol for water?', 'H2O', 'O2', 'CO2', 'NaCl', 1),
('Science', 'Which gas is most abundant in the Earth’s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Argon', 1),
('Science', 'Which organ is primarily responsible for pumping blood?', 'Heart', 'Liver', 'Kidney', 'Lung', 1),
('Science', 'What force keeps the planets in orbit around the Sun?', 'Gravity', 'Electromagnetism', 'Nuclear Force', 'Friction', 1),
('Science', 'Which simple machine is an inclined plane wrapped around a cylinder?', 'Screw', 'Lever', 'Pulley', 'Wheel and Axle', 1),
('Science', 'Which blood cells help fight infections?', 'White Blood Cells', 'Red Blood Cells', 'Platelets', 'Plasma Cells', 1),
('Science', 'In a food chain, which organisms are typically called producers?', 'Plants', 'Fungi', 'Herbivores', 'Bacteria', 1),
('Science', 'Which vitamin is primarily produced in human skin from sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin B12', 'Vitamin E', 1),
('Science', 'Which part of the cell contains genetic material in the form of DNA?', 'Nucleus', 'Cytoplasm', 'Cell Membrane', 'Mitochondrion', 1),
('Science', 'Which branch of science studies heavenly bodies such as stars, planets, and galaxies?', 'Astronomy', 'Geology', 'Meteorology', 'Astrology', 1),
('Science', 'Which gas do plants primarily take in for photosynthesis?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 2),
('Science', 'Which macromolecule is primarily responsible for carrying genetic information?', 'Lipids', 'DNA', 'Proteins', 'Carbohydrates', 2),
('Science', 'Who proposed the three laws of motion?', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Johannes Kepler', 2),
('Science', 'Which layer of Earth lies just below the crust?', 'Outer Core', 'Mantle', 'Inner Core', 'Lithosphere', 2),
('Science', 'Which type of symbiosis benefits both organisms involved?', 'Parasitism', 'Mutualism', 'Commensalism', 'Predation', 2),
('Science', 'Which element has the chemical symbol “He”?', 'Hydrogen', 'Helium', 'Hafnium', 'Helicon', 2),
('Science', 'Which scale is used to measure the acidity or alkalinity of a solution?', 'Richter Scale', 'pH Scale', 'Beaufort Scale', 'Scoville Scale', 2),
('Science', 'Which organ is responsible for filtering blood and producing urine?', 'Pancreas', 'Kidney', 'Heart', 'Spleen', 2),
('Science', 'Which tissue in plants conducts water and minerals from the roots?', 'Phloem', 'Xylem', 'Cambium', 'Cortex', 2),
('Science', 'Which scientist is famous for the theory of relativity?', 'Niels Bohr', 'Albert Einstein', 'Max Planck', 'Marie Curie', 2),
('Science', 'Which branch of science deals with the study of the atmosphere and weather?', 'Oceanography', 'Meteorology', 'Seismology', 'Ecology', 2),
('Science', 'Which biome is characterized by very low temperatures and permafrost?', 'Tropical Rainforest', 'Tundra', 'Desert', 'Savanna', 2),
('Science', 'Which planet is the second from the Sun?', 'Mercury', 'Earth', 'Venus', 'Mars', 3),
('Science', 'What type of cell division results in two daughter cells identical to the parent?', 'Meiosis', 'Binary Fission', 'Mitosis', 'Budding', 3),
('Science', 'Which molecule carries oxygen in red blood cells?', 'Collagen', 'Fibrinogen', 'Hemoglobin', 'Albumin', 3),
('Science', 'Which wave phenomenon explains the bending of waves around obstacles?', 'Reflection', 'Refraction', 'Diffraction', 'Interference', 3),
('Science', 'What is the positively charged particle in an atom’s nucleus?', 'Electron', 'Neutron', 'Proton', 'Neutrino', 3),
('Science', 'Which term describes animals that maintain their body temperature internally?', 'Ectotherms', 'Hemotherms', 'Endotherms', 'Thermophiles', 3),
('Science', 'Which large group of mammals includes whales, dolphins, and porpoises?', 'Marsupials', 'Rodents', 'Cetaceans', 'Primates', 3),
('Science', 'Which part of the brain is primarily responsible for balance and coordination?', 'Cerebrum', 'Medulla Oblongata', 'Cerebellum', 'Hypothalamus', 3),
('Science', 'Which branch of geology studies earthquakes and the propagation of elastic waves through Earth?', 'Volcanology', 'Petrology', 'Seismology', 'Mineralogy', 3),
('Science', 'Which layer of Earth\'s atmosphere contains the ozone layer?', 'Troposphere', 'Mesosphere', 'Stratosphere', 'Thermosphere', 3),
('Science', 'Which phase change occurs when a solid turns directly into a gas?', 'Freezing', 'Condensation', 'Sublimation', 'Deposition', 3),
('Science', 'Which phenomenon causes the apparent deflection of moving objects due to Earth’s rotation?', 'Greenhouse Effect', 'Refraction', 'Coriolis Effect', 'Doppler Effect', 3),
('Science', 'Which part of a plant conducts photosynthesis?', 'Root', 'Stem', 'Leaf', 'Flower', 3),
('Science', 'Which planet has the Great Red Spot, a giant storm?', 'Earth', 'Mars', 'Neptune', 'Jupiter', 4),
('Science', 'Which metal is liquid at room temperature?', 'Sodium', 'Potassium', 'Lead', 'Mercury', 4),
('Science', 'What is the largest artery in the human body?', 'Carotid Artery', 'Femoral Artery', 'Pulmonary Artery', 'Aorta', 4),
('Science', 'Which part of the Earth is composed primarily of liquid iron and nickel?', 'Crust', 'Mantle', 'Inner Core', 'Outer Core', 4),
('Science', 'Which scientist is known for formulating the laws of planetary motion?', 'Thomas Edison', 'Nikola Tesla', 'Galileo Galilei', 'Johannes Kepler', 4),
('Science', 'Which molecule forms the double helix structure discovered by Watson and Crick?', 'mRNA', 'rRNA', 'tRNA', 'DNA', 4),
('Science', 'Which gas is released by plants during photosynthesis?', 'Nitrogen', 'Carbon Dioxide', 'Methane', 'Oxygen', 4),
('Science', 'Which stage of matter has a definite volume but no fixed shape?', 'Solid', 'Plasma', 'Gas', 'Liquid', 4),
('Science', 'Which term describes organisms that break down dead or decaying organisms?', 'Producers', 'Primary Consumers', 'Secondary Consumers', 'Decomposers', 4),
('Science', 'Which number on the Mohs hardness scale corresponds to Diamond?', '7', '8', '9', '10', 4),
('Science', 'Which region of the electromagnetic spectrum has the longest wavelengths?', 'Visible Light', 'Ultraviolet', 'Infrared', 'Radio Waves', 4),
('Science', 'Which group of animals is defined by having fur, being warm-blooded, and typically bearing live young?', 'Amphibians', 'Reptiles', 'Birds', 'Mammals', 4),
('Science', 'Which periodic table group contains the noble gases?', 'Group 1 (Alkali Metals)', 'Group 2 (Alkaline Earth Metals)', 'Group 17 (Halogens)', 'Group 18', 4),


-- Pop-Culture Questions
('Pop-Culture', 'Which pop singer is also known as the \"Queen of Pop\"?', 'Madonna', 'Britney Spears', 'Beyoncé', 'Taylor Swift', 1),
('Pop-Culture', 'Which Netflix series popularized the phrase \"Friends Don\'t Lie\"?', 'Stranger Things', 'The Crown', 'Narcos', 'Ozark', 1),
('Pop-Culture', 'Which actor portrayed Captain Jack Sparrow in the \"Pirates of the Caribbean\" films?', 'Johnny Depp', 'Orlando Bloom', 'Keira Knightley', 'Geoffrey Rush', 1),
('Pop-Culture', 'Which superhero is part of DC Comics?', 'Batman', 'Iron Man', 'Spider-Man', 'Thor', 1),
('Pop-Culture', 'Which \"Lord of the Rings\" star played Frodo Baggins?', 'Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 'Orlando Bloom', 1),
('Pop-Culture', 'Which singer is famous for hits like \"Thriller\" and \"Billie Jean\"?', 'Michael Jackson', 'Prince', 'Stevie Wonder', 'Lionel Richie', 1),
('Pop-Culture', 'Which fast-food chain is known for its \"Golden Arches\"?', 'McDonald\'s', 'Burger King', 'Wendy\'s', 'Taco Bell', 1),
('Pop-Culture', 'Which movie features the character \"Forrest Gump\"?', 'Forrest Gump', 'Cast Away', 'Big', 'Saving Private Ryan', 1),
('Pop-Culture', 'Which actress starred as the lead in \"Legally Blonde\"?', 'Reese Witherspoon', 'Julia Roberts', 'Sandra Bullock', 'Jennifer Aniston', 1),
('Pop-Culture', 'Which singer is often referred to as \"The Boss\"?', 'Bruce Springsteen', 'Billy Joel', 'Jon Bon Jovi', 'Bob Dylan', 1),
('Pop-Culture', 'Which British band wrote \"Bohemian Rhapsody\"?', 'Queen', 'The Beatles', 'Pink Floyd', 'Led Zeppelin', 1),
('Pop-Culture', 'Which actress is known for her role as Hermione Granger in the Harry Potter film series?', 'Emma Watson', 'Emma Thompson', 'Maggie Smith', 'Evanna Lynch', 1),
('Pop-Culture', 'Which pop star gained fame with the single \"...Baby One More Time\"?', 'Christina Aguilera', 'Britney Spears', 'Madonna', 'Jessica Simpson', 2),
('Pop-Culture', 'Which 1990s sitcom featured the characters Ross, Rachel, and Chandler?', 'Seinfeld', 'Friends', 'Full House', 'Family Matters', 2),
('Pop-Culture', 'Which British singer is known for the album \"21\"?', 'Duffy', 'Adele', 'Amy Winehouse', 'Jessie J', 2),
('Pop-Culture', 'Which anime is famous for characters like Goku, Vegeta, and Gohan?', 'Naruto', 'Dragon Ball Z', 'One Piece', 'Bleach', 2),
('Pop-Culture', 'Which actor played Wolverine in the X-Men film series?', 'Ryan Reynolds', 'Hugh Jackman', 'Patrick Stewart', 'Ian McKellen', 2),
('Pop-Culture', 'Which streaming service produced \"The Witcher\" starring Henry Cavill?', 'Amazon Prime Video', 'Netflix', 'HBO Max', 'Hulu', 2),
('Pop-Culture', 'Which actress played the character Katniss Everdeen in \"The Hunger Games\" films?', 'Shailene Woodley', 'Jennifer Lawrence', 'Hailee Steinfeld', 'Emma Stone', 2),
('Pop-Culture', 'Which British fictional detective is based at 221B Baker Street?', 'Hercule Poirot', 'Sherlock Holmes', 'Miss Marple', 'Columbo', 2),
('Pop-Culture', 'Which pop star is known for hits like \"Shape of You\" and \"Thinking Out Loud\"?', 'Sam Smith', 'Ed Sheeran', 'Justin Timberlake', 'Shawn Mendes', 2),
('Pop-Culture', 'Which Marvel superhero has the alter-ego Peter Parker?', 'Captain America', 'Spider-Man', 'Hulk', 'Hawkeye', 2),
('Pop-Culture', 'Which actor is known for playing Tony Stark (Iron Man) in the Marvel Cinematic Universe?', 'Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 2),
('Pop-Culture', 'Which singer had a breakthrough hit with \"Just Dance\" in 2008?', 'Katy Perry', 'Lady Gaga', 'Rihanna', 'Taylor Swift', 2),
('Pop-Culture', 'Which sitcom is known for the line \"How you doin\'?\" from Joey Tribbiani?', 'Seinfeld', 'The Big Bang Theory', 'Friends', 'How I Met Your Mother', 3),
('Pop-Culture', 'Which band performed the song \"Hey Jude\"?', 'The Rolling Stones', 'Queen', 'The Beatles', 'The Who', 3),
('Pop-Culture', 'Which TV show features the characters Sheldon Cooper and Penny?', 'How I Met Your Mother', 'Modern Family', 'The Big Bang Theory', 'Friends', 3),
('Pop-Culture', 'Which classic rock band is known for \"Stairway to Heaven\"?', 'AC/DC', 'Pink Floyd', 'Led Zeppelin', 'The Doors', 3),
('Pop-Culture', 'Which director is famous for films such as \"Psycho\" and \"The Birds\"?', 'Steven Spielberg', 'Martin Scorsese', 'Alfred Hitchcock', 'Stanley Kubrick', 3),
('Pop-Culture', 'Which pop star performed the Super Bowl halftime show in 2020 alongside Jennifer Lopez?', 'Madonna', 'Beyoncé', 'Shakira', 'Rihanna', 3),
('Pop-Culture', 'Which band was fronted by Freddie Mercury?', 'The Rolling Stones', 'Pink Floyd', 'Queen', 'Genesis', 3),
('Pop-Culture', 'Which singer is known for the hit song \"Hello\" from 2015?', 'Rihanna', 'Taylor Swift', 'Adele', 'Selena Gomez', 3),
('Pop-Culture', 'Which animated TV show follows a boy and his adoptive brother, a magical dog?', 'Gravity Falls', 'Steven Universe', 'Adventure Time', 'Regular Show', 3),
('Pop-Culture', 'Which fantasy drama TV series is based on George R. R. Martin’s \"A Song of Ice and Fire\"?', 'The Witcher', 'Vikings', 'Game of Thrones', 'The Last Kingdom', 3),
('Pop-Culture', 'Which actor portrayed the character Deadpool in Marvel films?', 'Tom Holland', 'Chris Pratt', 'Ryan Reynolds', 'Chris Pine', 3),
('Pop-Culture', 'Which actor voices Woody in the \"Toy Story\" films?', 'Tim Allen', 'Don Rickles', 'Tom Hanks', 'John Ratzenberger', 3),
('Pop-Culture', 'Which video game franchise features a plumber traveling through the Mushroom Kingdom?', 'Sonic the Hedgehog', 'The Legend of Zelda', 'Super Mario', 'Minecraft', 3),
('Pop-Culture', 'Which long-running TV show is set in the fictional town of Springfield?', 'Family Guy', 'South Park', 'King of the Hill', 'The Simpsons', 4),
('Pop-Culture', 'Which singer is known for hits like \"Umbrella\" and \"Diamonds\"?', 'Beyoncé', 'Ariana Grande', 'Nicki Minaj', 'Rihanna', 4),
('Pop-Culture', 'Which author wrote the \"Harry Potter\" series?', 'Stephenie Meyer', 'Suzanne Collins', 'J.R.R. Tolkien', 'J.K. Rowling', 4),
('Pop-Culture', 'Which streaming service released the original series \"The Mandalorian\"?', 'Netflix', 'HBO Max', 'Amazon Prime Video', 'Disney+', 4),
('Pop-Culture', 'Which film franchise features Luke Skywalker and Darth Vader?', 'Star Trek', 'Dune', 'Harry Potter', 'Star Wars', 4),
('Pop-Culture', 'Which singer is known for the single \"Shake It Off\"?', 'Kesha', 'Avril Lavigne', 'Britney Spears', 'Taylor Swift', 4),
('Pop-Culture', 'Which fantasy series was written by J.R.R. Tolkien?', 'The Chronicles of Narnia', 'A Song of Ice and Fire', 'The Wheel of Time', 'The Lord of the Rings', 4),
('Pop-Culture', 'Which TV show follows a high school chemistry teacher turned meth producer?', 'Mad Men', 'Ozark', 'Narcos', 'Breaking Bad', 4),
('Pop-Culture', 'Which singer is known by the nickname \"Queen Bey\"?', 'Alicia Keys', 'Mariah Carey', 'Cardi B', 'Beyoncé', 4),
('Pop-Culture', 'Which artist is famous for painting the \"Mona Lisa\"?', 'Michelangelo', 'Raphael', 'Donatello', 'Leonardo da Vinci', 4),
('Pop-Culture', 'Which game series includes characters like Pikachu and Charizard?', 'Digimon', 'Yu-Gi-Oh!', 'Monster Hunter', 'Pokémon', 4),
('Pop-Culture', 'Which actress famously portrayed Black Widow in the Marvel Cinematic Universe?', 'Elizabeth Olsen', 'Brie Larson', 'Scarlett Johansson', 'Natalie Portman', 4),
('Pop-Culture', 'Which classic arcade game features a yellow character eating pellets in a maze?', 'Space Invaders', 'Galaga', 'Donkey Kong', 'Pac-Man', 4),


-- Wild Questions
('Wild', 'Which 1993 film features dinosaurs recreated through genetic engineering?', 'Jurassic Park', 'The Lost World', 'King Kong', 'Dinosaur', 1),
('Wild', 'Which zodiac sign is represented by the Twins?', 'Gemini', 'Cancer', 'Pisces', 'Leo', 1),
('Wild', 'Who discovered penicillin by accident in 1928?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Edward Jenner', 1),
('Wild', 'In Greek mythology, who is the god of the underworld?', 'Hades', 'Poseidon', 'Ares', 'Apollo', 1),
('Wild', 'Which US President is on the $1 bill?', 'George Washington', 'Abraham Lincoln', 'Benjamin Franklin', 'Thomas Jefferson', 1),
('Wild', 'Which chemical element primarily makes up diamonds?', 'Carbon', 'Silicon', 'Iron', 'Sulfur', 1),
('Wild', 'Which Italian city is the setting for Shakespeare’s \"Romeo and Juliet\"?', 'Verona', 'Venice', 'Florence', 'Milan', 1),
('Wild', 'Which mathematical constant is approximately 3.14159?', 'Pi', 'Euler’s Number', 'Golden Ratio', 'Imaginary Unit', 1),
('Wild', 'Which planet in the Solar System rotates on its side?', 'Uranus', 'Venus', 'Neptune', 'Jupiter', 1),
('Wild', 'Which fictional detective was created by Sir Arthur Conan Doyle?', 'Sherlock Holmes', 'Hercule Poirot', 'Miss Marple', 'Sam Spade', 1),
('Wild', 'Which layer of the Earth do humans live on?', 'Crust', 'Mantle', 'Outer Core', 'Inner Core', 1),
('Wild', 'Which species is the largest fish in the ocean?', 'Whale Shark', 'Great White Shark', 'Blue Whale (mammal)', 'Manta Ray', 1),
('Wild', 'Which is the largest land mammal on Earth?', 'Hippopotamus', 'African Elephant', 'Rhinoceros', 'Giraffe', 2),
('Wild', 'Which programming language was created by Guido van Rossum?', 'Ruby', 'Python', 'Java', 'C++', 2),
('Wild', 'Which part of the cell is often called the \"powerhouse\"?', 'Golgi apparatus', 'Mitochondria', 'Ribosome', 'Nucleus', 2),
('Wild', 'Which actor portrayed Jack Dawson in the film \"Titanic\"?', 'Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Matthew McConaughey', 2),
('Wild', 'Which chemical element has the symbol \"Au\"?', 'Silver', 'Gold', 'Copper', 'Iron', 2),
('Wild', 'Which Marvel superhero is nicknamed the \"Merc with a Mouth\"?', 'Hawkeye', 'Deadpool', 'Doctor Strange', 'Black Panther', 2),
('Wild', 'Which country is the origin of the martial art Taekwondo?', 'Japan', 'South Korea', 'China', 'Thailand', 2),
('Wild', 'Which style of Japanese comic books has gained global popularity?', 'Manhwa', 'Manga', 'Comics', 'Doujinshi', 2),
('Wild', 'Which chess piece can only move diagonally?', 'Rook', 'Bishop', 'Knight', 'Queen', 2),
('Wild', 'Which Greek letter is used to represent the golden ratio (~1.618)?', 'Theta (Θ)', 'Phi (Φ)', 'Omega (Ω)', 'Alpha (Α)', 2),
('Wild', 'Which single-celled organism is noted for its shape-shifting ability and ingestion method called phagocytosis?', 'Paramecium', 'Amoeba', 'Euglena', 'Volvox', 2),
('Wild', 'Which fast-food chain is famous for its \"Whopper\" burger?', 'Arby’s', 'Burger King', 'Carl’s Jr.', 'Jack in the Box', 2),
('Wild', 'Which is the tallest mountain in North America?', 'Mount Rainier', 'Mount Whitney', 'Denali (Mount McKinley)', 'Mount Logan', 3),
('Wild', 'Which color do you get by mixing blue and yellow in subtractive color mixing?', 'Purple', 'Orange', 'Green', 'Brown', 3),
('Wild', 'Which chemical element has the atomic number 8?', 'Carbon', 'Hydrogen', 'Oxygen', 'Nitrogen', 3),
('Wild', 'Which city is the capital of the U.S. state of Georgia?', 'Savannah', 'Athens', 'Atlanta', 'Augusta', 3),
('Wild', 'Which popular video game involves mining resources and building structures from blocks?', 'Terraria', 'Roblox', 'Minecraft', 'Fortnite', 3),
('Wild', 'Which large dog breed is known for alpine rescues, sometimes depicted with a small barrel around its neck?', 'Newfoundland', 'Great Dane', 'St. Bernard', 'Bernese Mountain Dog', 3),
('Wild', 'Which chess piece moves in an L-shape?', 'Bishop', 'King', 'Knight', 'Rook', 3),
('Wild', 'Which type of waves are used for mobile phone communication?', 'Gamma Rays', 'Microwaves', 'Radio Waves', 'Infrared', 3),
('Wild', 'Which U.S. holiday commemorates the end of slavery in 1865?', 'Martin Luther King Jr. Day', 'Emancipation Proclamation Day', 'Juneteenth', 'Labor Day', 3),
('Wild', 'Which fruit is often called the \"King of Fruits\" in many Asian countries?', 'Mango', 'Pineapple', 'Durian', 'Jackfruit', 3),
('Wild', 'Which virus caused a global pandemic that began in late 2019?', 'Influenza A', 'Ebola virus', 'SARS-CoV-2', 'Zika virus', 3),
('Wild', 'Which bird has the largest wingspan of any living bird?', 'Andean Condor', 'Marabou Stork', 'Wandering Albatross', 'Royal Albatross', 3),
('Wild', 'Which sea creature is known for having three hearts?', 'Starfish', 'Sea Urchin', 'Octopus', 'Jellyfish', 3),
('Wild', 'Which ancient wonder stood in the city of Halicarnassus?', 'Hanging Gardens', 'Colossus of Rhodes', 'Temple of Artemis', 'Mausoleum at Halicarnassus', 4),
('Wild', 'Which vitamin is well-known for its antioxidant properties and is abundant in citrus fruits?', 'Vitamin B12', 'Vitamin D', 'Vitamin K', 'Vitamin C', 4),
('Wild', 'Which instrument is used to measure atmospheric pressure?', 'Thermometer', 'Hygrometer', 'Anemometer', 'Barometer', 4),
('Wild', 'Which famous ship sank in 1912 after hitting an iceberg?', 'Lusitania', 'Carpathia', 'Britannic', 'RMS Titanic', 4),
('Wild', 'Which planet is recognized for its extensive ring system?', 'Jupiter', 'Neptune', 'Uranus', 'Saturn', 4),
('Wild', 'Which chemical formula represents common table salt?', 'CO2', 'H2SO4', 'KCl', 'NaCl', 4),
('Wild', 'Which oceanic phenomenon involves periodic warming of the equatorial Pacific waters?', 'La Niña', 'Monsoon', 'Thermohaline Circulation', 'El Niño', 4),
('Wild', 'Which wedge-shaped writing system was used in ancient Mesopotamia?', 'Hieroglyphics', 'Runes', 'Linear B', 'Cuneiform', 4),
('Wild', 'Which U.S. state is nicknamed \"The Last Frontier\"?', 'Hawaii', 'Montana', 'Wyoming', 'Alaska', 4),
('Wild', 'Which martial art is often referred to as the \"Gentle Way\"?', 'Taekwondo', 'Karate', 'Aikido', 'Judo', 4),
('Wild', 'Which animal is the largest rodent in the world?', 'Beaver', 'Guinea Pig', 'Chinchilla', 'Capybara', 4),
('Wild', 'Which scale is used to measure the heat (spiciness) of chili peppers?', 'Richter Scale', 'Mercalli Scale', 'PH Scale', 'Scoville Scale', 4),
('Wild', 'Which scientist was the first woman to win a Nobel Prize and conducted pioneering research on radioactivity?', 'Rosalind Franklin', 'Lise Meitner', 'Irène Joliot-Curie', 'Marie Curie', 4);


