INSERT INTO `trivniac`.`questions` (category, question, option_1, option_2, option_3, option_4, answer) VALUES
-- History Questions
('History', 'Who was the first U.S. President to resign?', 'Andrew Johnson', 'Richard Nixon', 'Bill Clinton', 'Herbert Hoover', 2),
('History', 'The Great Fire of London occurred in which year?', '1666', '1701', '1803', '1575', 1),
('History', 'What was the first battle of the American Revolution?', 'Battle of Bunker Hill', 'Battle of Yorktown', 'Battle of Lexington and Concord', 'Battle of Saratoga', 3),
('History', 'Who wrote the Communist Manifesto?', 'Karl Marx & Friedrich Engels', 'Vladimir Lenin', 'Joseph Stalin', 'Adam Smith', 1),
('History', 'Which U.S. state was an independent country before joining the Union?', 'California', 'Texas', 'Florida', 'Alaska', 2),
('History', 'Who was the longest-serving British monarch?', 'Victoria', 'George III', 'Elizabeth II', 'Henry VIII', 3),
('History', 'Which civilization built the city of Tenochtitlan?', 'Aztecs', 'Mayans', 'Incas', 'Romans', 1),
('History', 'What was the first capital city of the United States?', 'New York City', 'Philadelphia', 'Washington, D.C.', 'Boston', 1),
('History', 'What year did the Berlin Wall fall?', '1985', '1989', '1991', '1993', 2),
('History', 'Which U.S. President signed the Emancipation Proclamation?', 'George Washington', 'Theodore Roosevelt', 'Abraham Lincoln', 'Andrew Jackson', 3),
('History', 'The Wright brothers made their first flight in what year?', '1895', '1903', '1912', '1920', 2),
('History', 'Who was the first Emperor of China?', 'Qin Shi Huang', 'Confucius', 'Sun Tzu', 'Genghis Khan', 1),
('History', 'The Treaty of Versailles officially ended which war?', 'World War I', 'World War II', 'Napoleonic Wars', 'American Civil War', 1),
('History', 'Who was the first U.S. President to appear on television?', 'Franklin D. Roosevelt', 'John F. Kennedy', 'Harry S. Truman', 'Dwight Eisenhower', 1),
('History', 'Who was the first female ruler of Ancient Egypt?', 'Cleopatra', 'Nefertiti', 'Hatshepsut', 'Arsinoe', 3),
('History', 'Which war was famously fought over Helen of Troy?', 'Peloponnesian War', 'Punic Wars', 'Trojan War', 'Hundred Years War', 3),
('History', 'Which famous leader was assassinated on the Ides of March?', 'Julius Caesar', 'Alexander the Great', 'Napoleon Bonaparte', 'Genghis Khan', 1),
('History', 'Which explorer first circumnavigated the world?', 'Christopher Columbus', 'Ferdinand Magellan', 'James Cook', 'Marco Polo', 2),
('History', 'Who was known as the "Iron Lady"?', 'Margaret Thatcher', 'Indira Gandhi', 'Angela Merkel', 'Golda Meir', 1),
('History', 'Which ancient civilization invented the first writing system?', 'Romans', 'Egyptians', 'Sumerians', 'Greeks', 3),
('History', 'What was the name of the ship that brought the Pilgrims to America?', 'Santa Maria', 'Endeavour', 'Mayflower', 'Beagle', 3),
('History', 'Who was the first U.S. president to be impeached?', 'Richard Nixon', 'Andrew Johnson', 'Bill Clinton', 'Donald Trump', 2),
('History', 'Which U.S. state was the last to join the United States?', 'Hawaii', 'Alaska', 'New Mexico', 'Arizona', 1),
('History', 'The Boston Tea Party protested against which country?', 'France', 'Spain', 'Great Britain', 'Germany', 3),
('History', 'Who discovered the Americas in 1492?', 'Leif Erikson', 'Christopher Columbus', 'Marco Polo', 'Amerigo Vespucci', 2),
('History', 'Who was the leader of the Soviet Union during World War II?', 'Vladimir Lenin', 'Joseph Stalin', 'Mikhail Gorbachev', 'Leon Trotsky', 2),
('History', 'What year did the U.S. enter World War II?', '1939', '1941', '1943', '1945', 2),
('History', 'Which ancient wonder was located in Egypt?', 'Colossus of Rhodes', 'Hanging Gardens of Babylon', 'Great Pyramid of Giza', 'Temple of Artemis', 3),
('History', 'The Rosetta Stone helped decipher which language?', 'Greek', 'Latin', 'Hieroglyphics', 'Cuneiform', 3),
('History', 'Which empire was ruled by Julius Caesar?', 'Roman Empire', 'Byzantine Empire', 'Ottoman Empire', 'Persian Empire', 1),
('History', 'Who was the first President to live in the White House?', 'George Washington', 'John Adams', 'Thomas Jefferson', 'James Madison', 2),
('History', 'The Louisiana Purchase was made by which U.S. President?', 'George Washington', 'Thomas Jefferson', 'Andrew Jackson', 'James Monroe', 2),
('History', 'Which war lasted from 1955 to 1975?', 'Korean War', 'Vietnam War', 'World War II', 'Persian Gulf War', 2),
('History', 'Who was the first African American U.S. President?', 'Barack Obama', 'Colin Powell', 'Jesse Jackson', 'Frederick Douglass', 1),
('History', 'Who led the Soviet Union during the Cuban Missile Crisis?', 'Leon Trotsky', 'Nikita Khrushchev', 'Joseph Stalin', 'Mikhail Gorbachev', 2),
('History', 'Which year marked the beginning of the Great Depression?', '1919', '1929', '1939', '1949', 2),
('History', 'Who was the Prime Minister of the UK during most of World War II?', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden', 2),
('History', 'The Cold War was mainly between which two nations?', 'USA & Japan', 'USA & Soviet Union', 'USA & China', 'USA & Germany', 2),
('History', 'Which document begins with "We the People"?', 'Declaration of Independence', 'U.S. Constitution', 'Bill of Rights', 'Emancipation Proclamation', 2),
('History', 'Which U.S. President delivered the Gettysburg Address?', 'Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'Theodore Roosevelt', 3),
('History', 'Which country gifted the Statue of Liberty to the United States?', 'United Kingdom', 'France', 'Italy', 'Germany', 2),
('History', 'What was the first battle of the U.S. Civil War?', 'Battle of Gettysburg', 'Battle of Antietam', 'Battle of Fort Sumter', 'Battle of Shiloh', 3),
('History', 'Which U.S. President made the Louisiana Purchase?', 'Thomas Jefferson', 'James Madison', 'Andrew Jackson', 'George Washington', 1),
('History', 'Who discovered penicillin?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Jonas Salk', 1),
('History', 'Which U.S. President gave the famous "I Have a Dream" speech?', 'Lyndon B. Johnson', 'John F. Kennedy', 'None (Martin Luther King Jr.)', 'Franklin D. Roosevelt', 3),
('History', 'What year did the United Nations officially form?', '1919', '1945', '1950', '1961', 2),
('History', 'Which war was fought between the North and South regions of the United States?', 'American Revolution', 'War of 1812', 'U.S. Civil War', 'Mexican-American War', 3),
('History', 'Who was the first woman to fly solo across the Atlantic Ocean?', 'Amelia Earhart', 'Sally Ride', 'Bessie Coleman', 'Harriet Quimby', 1),
('History', 'Which country built the first working steam locomotive?', 'United States', 'Germany', 'United Kingdom', 'France', 3),
('History', 'Which event led to the start of World War I?', 'Pearl Harbor attack', 'Assassination of Archduke Franz Ferdinand', 'Sinking of Lusitania', 'Invasion of Poland', 2),

-- Sports Questions
('Sports', 'Which sport is known as "The Gentlemen’s Game"?', 'Cricket', 'Tennis', 'Golf', 'Polo', 1),
('Sports', 'How many players are on a standard soccer team?', '9', '10', '11', '12', 3),
('Sports', 'Which country has won the most FIFA World Cups?', 'Brazil', 'Germany', 'Italy', 'Argentina', 1),
('Sports', 'In what year did the first modern Olympic Games take place?', '1896', '1900', '1924', '1932', 1),
('Sports', 'Which team has won the most NBA championships?', 'Los Angeles Lakers', 'Boston Celtics', 'Chicago Bulls', 'Golden State Warriors', 2),
('Sports', 'Who is the all-time top scorer in the Premier League?', 'Cristiano Ronaldo', 'Alan Shearer', 'Wayne Rooney', 'Lionel Messi', 2),
('Sports', 'Which sport is played at Wimbledon?', 'Tennis', 'Cricket', 'Baseball', 'Golf', 1),
('Sports', 'What is the maximum score in a single frame of bowling?', '20', '30', '40', '50', 2),
('Sports', 'Which U.S. city hosted the 1996 Summer Olympics?', 'Los Angeles', 'Atlanta', 'New York', 'Chicago', 2),
('Sports', 'How long is a marathon?', '20 miles', '26.2 miles', '30 miles', '40 miles', 2),
('Sports', 'Which country is known for inventing ice hockey?', 'United States', 'Russia', 'Canada', 'Sweden', 3),
('Sports', 'What is the national sport of Japan?', 'Sumo Wrestling', 'Baseball', 'Karate', 'Judo', 1),
('Sports', 'How many periods are there in an ice hockey game?', '2', '3', '4', '5', 2),
('Sports', 'Which athlete has won the most Olympic gold medals?', 'Michael Phelps', 'Usain Bolt', 'Carl Lewis', 'Simone Biles', 1),
('Sports', 'Which sport uses a shuttlecock?', 'Badminton', 'Tennis', 'Squash', 'Table Tennis', 1),
('Sports', 'What is the diameter of a basketball hoop in inches?', '15', '18', '21', '24', 2),
('Sports', 'Which football club is known as "The Red Devils"?', 'Chelsea', 'Liverpool', 'Manchester United', 'Arsenal', 3),
('Sports', 'What is the maximum score in gymnastics?', '10', '100', '50', '25', 1),
('Sports', 'Which Grand Slam tennis tournament is played on a clay court?', 'Australian Open', 'French Open', 'Wimbledon', 'US Open', 2),
('Sports', 'How many points is a field goal worth in American football?', '3', '6', '7', '1', 1),
('Sports', 'Who holds the record for the fastest 100m sprint?', 'Carl Lewis', 'Usain Bolt', 'Jesse Owens', 'Tyson Gay', 2),
('Sports', 'What is the national sport of Canada?', 'Baseball', 'Lacrosse', 'Ice Hockey', 'Basketball', 2),
('Sports', 'Which team won the first Super Bowl?', 'Dallas Cowboys', 'Green Bay Packers', 'Kansas City Chiefs', 'Pittsburgh Steelers', 2),
('Sports', 'What is the distance of a standard swimming pool used in the Olympics?', '25 meters', '50 meters', '100 meters', '75 meters', 2),
('Sports', 'Which famous golfer has won the most Masters tournaments?', 'Jack Nicklaus', 'Tiger Woods', 'Arnold Palmer', 'Phil Mickelson', 1),
('Sports', 'What is the term for three strikes in a row in bowling?', 'Turkey', 'Spare', 'Double', 'Strike', 1),
('Sports', 'What is the maximum number of clubs a golfer can carry?', '12', '14', '16', '18', 2),
('Sports', 'Which boxer was nicknamed "The Greatest"?', 'Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'George Foreman', 2),
('Sports', 'Which baseball team has won the most World Series titles?', 'New York Yankees', 'Boston Red Sox', 'Los Angeles Dodgers', 'Chicago Cubs', 1),
('Sports', 'What is the standard size of a soccer goal?', '8x20 feet', '8x24 feet', '10x26 feet', '7x21 feet', 2),
('Sports', 'Which tennis player has won the most Grand Slam titles?', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Pete Sampras', 3),
('Sports', 'What does FIFA stand for?', 'Federation of International Football Associations', 'Football International Federation Association', 'Federation Internationale de Football Association', 'Football Institution Federation Association', 3),
('Sports', 'Who is the only athlete to play in a Super Bowl and a World Series?', 'Michael Jordan', 'Bo Jackson', 'Deion Sanders', 'Jim Thorpe', 3),
('Sports', 'Which famous cyclist won seven Tour de France titles before being stripped of them?', 'Lance Armstrong', 'Eddy Merckx', 'Miguel Indurain', 'Chris Froome', 1),
('Sports', 'What color is the center scoring circle in archery?', 'Blue', 'Red', 'Black', 'Gold', 4),
('Sports', 'In what sport would you find a pommel horse?', 'Gymnastics', 'Equestrian', 'Rodeo', 'Fencing', 1),
('Sports', 'What is the term for hitting a baseball out of the park?', 'Strike', 'Home Run', 'Grand Slam', 'Foul', 2),
('Sports', 'What is the oldest tennis tournament in the world?', 'Australian Open', 'French Open', 'Wimbledon', 'US Open', 3),
('Sports', 'What country hosted the 2016 Summer Olympics?', 'China', 'Brazil', 'United Kingdom', 'United States', 2),
('Sports', 'Which sport uses the term "love" for a score of zero?', 'Badminton', 'Tennis', 'Table Tennis', 'Squash', 2),
('Sports', 'What is the most popular sport in the world?', 'Soccer', 'Basketball', 'Cricket', 'Tennis', 1),
('Sports', 'Which country won the first-ever FIFA World Cup?', 'Argentina', 'Brazil', 'Uruguay', 'Germany', 3),
('Sports', 'What does a baseball player hit with a bat?', 'Basketball', 'Cricket Ball', 'Baseball', 'Golf Ball', 3),
('Sports', 'Which race is known as "The Fastest Two Minutes in Sports"?', 'The Belmont Stakes', 'The Preakness Stakes', 'The Kentucky Derby', 'The Grand National', 3),
('Sports', 'What is the regulation height of a basketball hoop?', '10 feet', '12 feet', '8 feet', '9 feet', 1),
('Sports', 'What is the name of the trophy awarded in the NHL?', 'Stanley Cup', 'Lombardi Trophy', 'World Cup', 'Claret Jug', 1),
('Sports', 'Which sport uses a net, a shuttlecock, and a racket?', 'Tennis', 'Badminton', 'Squash', 'Pickleball', 2),
('Sports', 'Which city hosted the 2000 Summer Olympics?', 'Sydney', 'Athens', 'Beijing', 'London', 1),
('Sports', 'Which athlete has won the most gold medals in track and field?', 'Carl Lewis', 'Usain Bolt', 'Paavo Nurmi', 'Jesse Owens', 2),
('Sports', 'What is the circumference of a standard basketball?', '25 inches', '28.5 inches', '29.5 inches', '31 inches', 3),


-- Geography Questions
('Geography', 'What is the largest country by land area?', 'China', 'Russia', 'United States', 'Canada', 2),
('Geography', 'What is the smallest country in the world?', 'Monaco', 'Vatican City', 'Liechtenstein', 'San Marino', 2),
('Geography', 'What is the longest river in the world?', 'Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River', 2),
('Geography', 'Which continent has the most countries?', 'Africa', 'Asia', 'Europe', 'South America', 1),
('Geography', 'Which U.S. state has the longest coastline?', 'California', 'Florida', 'Hawaii', 'Alaska', 4),
('Geography', 'What is the highest mountain in North America?', 'Mount McKinley (Denali)', 'Mount Everest', 'Mount Kilimanjaro', 'Mount Elbert', 1),
('Geography', 'Which ocean is the largest?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 4),
('Geography', 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 3),
('Geography', 'Which country has the most natural lakes?', 'United States', 'Canada', 'Russia', 'Brazil', 2),
('Geography', 'Which country is home to the Amazon Rainforest?', 'Peru', 'Brazil', 'Colombia', 'Ecuador', 2),
('Geography', 'What is the driest continent?', 'Africa', 'Antarctica', 'Australia', 'Europe', 2),
('Geography', 'Which country has the highest population?', 'India', 'United States', 'China', 'Indonesia', 3),
('Geography', 'Which desert is the largest in the world?', 'Sahara', 'Antarctica', 'Gobi', 'Kalahari', 2),
('Geography', 'Which country has the most volcanoes?', 'Japan', 'Indonesia', 'United States', 'Philippines', 2),
('Geography', 'What is the name of the river that runs through Egypt?', 'Amazon', 'Nile', 'Yangtze', 'Ganges', 2),
('Geography', 'What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 2),
('Geography', 'Which European country is known for its fjords?', 'Norway', 'Sweden', 'Finland', 'Denmark', 1),
('Geography', 'Which country is also a continent?', 'Greenland', 'Australia', 'Iceland', 'New Zealand', 2),
('Geography', 'Which island is the largest in the world?', 'Greenland', 'Madagascar', 'Borneo', 'Iceland', 1),
('Geography', 'What is the name of the largest coral reef system?', 'The Great Barrier Reef', 'Belize Barrier Reef', 'Andros Barrier Reef', 'Red Sea Coral Reef', 1),
('Geography', 'Which African country was never colonized?', 'Egypt', 'South Africa', 'Ethiopia', 'Ghana', 3),
('Geography', 'Which two countries share the longest international border?', 'USA & Canada', 'Russia & China', 'Brazil & Argentina', 'India & Pakistan', 1),
('Geography', 'Which city is known as "The Eternal City"?', 'Athens', 'Rome', 'Paris', 'Jerusalem', 2),
('Geography', 'Which country is known as the Land of the Rising Sun?', 'China', 'South Korea', 'Japan', 'Vietnam', 3),
('Geography', 'Which U.S. state has the most islands?', 'Hawaii', 'Alaska', 'Florida', 'California', 2),
('Geography', 'Which sea separates Europe from Africa?', 'Baltic Sea', 'Black Sea', 'Mediterranean Sea', 'Caribbean Sea', 3),
('Geography', 'What is the capital of Brazil?', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Buenos Aires', 3),
('Geography', 'Which mountain range separates Europe and Asia?', 'Alps', 'Rockies', 'Urals', 'Himalayas', 3),
('Geography', 'Which city is known for the Eiffel Tower?', 'London', 'Berlin', 'Paris', 'Rome', 3),
('Geography', 'What is the largest U.S. state by area?', 'Texas', 'California', 'Alaska', 'Montana', 3),
('Geography', 'Which country is home to the world’s tallest waterfall, Angel Falls?', 'Peru', 'Brazil', 'Venezuela', 'Argentina', 3),
('Geography', 'Which country is completely surrounded by South Africa?', 'Lesotho', 'Eswatini', 'Namibia', 'Botswana', 1),
('Geography', 'Which European capital city is built on 14 islands?', 'Stockholm', 'Copenhagen', 'Amsterdam', 'Oslo', 1),
('Geography', 'Which U.S. state is closest to Russia?', 'Washington', 'Alaska', 'California', 'Oregon', 2),
('Geography', 'What is the capital of Mexico?', 'Monterrey', 'Mexico City', 'Guadalajara', 'Tijuana', 2),
('Geography', 'Which country has the largest population in South America?', 'Argentina', 'Colombia', 'Brazil', 'Peru', 3),
('Geography', 'Which country has the most UNESCO World Heritage Sites?', 'Italy', 'China', 'United States', 'Spain', 1),
('Geography', 'What is the name of the line that divides the Earth into the Northern and Southern Hemispheres?', 'Prime Meridian', 'Tropic of Cancer', 'Equator', 'International Date Line', 3),
('Geography', 'What is the capital of Thailand?', 'Ho Chi Minh City', 'Jakarta', 'Bangkok', 'Manila', 3),
('Geography', 'What is the name of the sea between Japan and Korea?', 'Yellow Sea', 'Sea of Japan', 'East China Sea', 'Philippine Sea', 2),
('Geography', 'Which river is the longest in South America?', 'Amazon', 'Orinoco', 'Paraná', 'Magdalena', 1),
('Geography', 'Which island country is known as the "Pearl of the Indian Ocean"?', 'Maldives', 'Sri Lanka', 'Seychelles', 'Madagascar', 2),
('Geography', 'Which U.S. state is the only one to have a tropical rainforest?', 'Hawaii', 'Florida', 'Oregon', 'California', 1),
('Geography', 'Which European river passes through the most countries?', 'Danube', 'Rhine', 'Seine', 'Volga', 1),
('Geography', 'What is the name of the bridge that connects San Francisco to Marin County?', 'Brooklyn Bridge', 'Golden Gate Bridge', 'Tower Bridge', 'Bay Bridge', 2),
('Geography', 'Which country has the longest coastline in the world?', 'United States', 'Canada', 'Russia', 'Australia', 2),
('Geography', 'What is the only country that spans both Asia and Europe?', 'Turkey', 'Russia', 'Kazakhstan', 'Mongolia', 2),
('Geography', 'What is the capital of South Korea?', 'Beijing', 'Seoul', 'Tokyo', 'Bangkok', 2),
('Geography', 'Which African lake is the second-largest freshwater lake in the world?', 'Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad', 1),
('Geography', 'Which U.S. state is home to the Grand Canyon?', 'Nevada', 'Arizona', 'Utah', 'Colorado', 2),


-- Science Questions
('Science', 'What is the chemical symbol for water?', 'O2', 'H2O', 'CO2', 'NaCl', 2),
('Science', 'What planet is known as the Red Planet?', 'Earth', 'Venus', 'Mars', 'Jupiter', 3),
('Science', 'Which gas is most abundant in Earth’s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 3),
('Science', 'Who developed the theory of relativity?', 'Isaac Newton', 'Nikola Tesla', 'Albert Einstein', 'Galileo Galilei', 3),
('Science', 'What type of blood cells help fight infection?', 'Red blood cells', 'White blood cells', 'Platelets', 'Plasma', 2),
('Science', 'What is the hardest natural substance on Earth?', 'Gold', 'Diamond', 'Iron', 'Quartz', 2),
('Science', 'Which part of the brain controls balance?', 'Cerebrum', 'Cerebellum', 'Medulla', 'Thalamus', 2),
('Science', 'How many bones are in the adult human body?', '206', '208', '210', '212', 1),
('Science', 'Which element has the highest atomic number?', 'Uranium', 'Plutonium', 'Oganesson', 'Neon', 3),
('Science', 'Which planet rotates on its side?', 'Venus', 'Mars', 'Uranus', 'Neptune', 3),
('Science', 'What is the most abundant element in the universe?', 'Oxygen', 'Carbon', 'Hydrogen', 'Helium', 3),
('Science', 'Which blood type is known as the universal donor?', 'A', 'B', 'O-', 'AB', 3),
('Science', 'Which gas do plants absorb during photosynthesis?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 2),
('Science', 'What is the chemical symbol for gold?', 'Ag', 'Au', 'Pb', 'Fe', 2),
('Science', 'How long does it take for the Earth to orbit the Sun?', '24 hours', '30 days', '365 days', '10 years', 3),
('Science', 'What is the name of the largest internal organ in the human body?', 'Heart', 'Liver', 'Lungs', 'Stomach', 2),
('Science', 'What is the speed of light?', '186,000 miles per second', '150,000 miles per second', '250,000 miles per second', '1,000 miles per second', 1),
('Science', 'Which part of the cell contains DNA?', 'Cytoplasm', 'Nucleus', 'Mitochondria', 'Ribosome', 2),
('Science', 'What is the process by which plants make their food?', 'Respiration', 'Photosynthesis', 'Fermentation', 'Evaporation', 2),
('Science', 'Which famous scientist discovered penicillin?', 'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Isaac Newton', 2),
('Science', 'Which blood type is known as the universal recipient?', 'O+', 'B-', 'AB+', 'A-', 3),
('Science', 'Which organ pumps blood throughout the body?', 'Brain', 'Liver', 'Heart', 'Lungs', 3),
('Science', 'What is the boiling point of water in Celsius?', '50°C', '75°C', '100°C', '120°C', 3),
('Science', 'Which vitamin is produced when human skin is exposed to sunlight?', 'Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin B12', 3),
('Science', 'What part of the eye controls how much light enters?', 'Lens', 'Cornea', 'Iris', 'Retina', 3),
('Science', 'Which animal has the largest brain?', 'Elephant', 'Dolphin', 'Blue Whale', 'Gorilla', 3),
('Science', 'What is the name of the force that keeps us on Earth?', 'Magnetism', 'Friction', 'Gravity', 'Inertia', 3),
('Science', 'Which gas makes up most of the Sun’s mass?', 'Oxygen', 'Nitrogen', 'Hydrogen', 'Helium', 3),
('Science', 'How many planets are in our solar system?', '7', '8', '9', '10', 2),
('Science', 'What is the smallest unit of life?', 'Atom', 'Molecule', 'Cell', 'Organ', 3),
('Science', 'What is the pH of pure water?', '5', '6', '7', '8', 3),
('Science', 'Which metal is liquid at room temperature?', 'Iron', 'Gold', 'Mercury', 'Copper', 3),
('Science', 'What do we call the bending of light as it passes through different materials?', 'Reflection', 'Refraction', 'Diffraction', 'Dispersion', 2),
('Science', 'Which scientist is known for formulating the laws of motion?', 'Galileo Galilei', 'Isaac Newton', 'Albert Einstein', 'Charles Darwin', 2),
('Science', 'Which animal can live the longest?', 'Tortoise', 'Whale Shark', 'Elephant', 'Blue Whale', 1),
('Science', 'What do bees collect to make honey?', 'Water', 'Pollen', 'Nectar', 'Leaves', 3),
('Science', 'Which part of the human brain controls emotions?', 'Cerebrum', 'Hippocampus', 'Amygdala', 'Cerebellum', 3),
('Science', 'Which human sense is the most sensitive?', 'Sight', 'Hearing', 'Smell', 'Taste', 3),
('Science', 'Which is the largest land carnivore?', 'Lion', 'Tiger', 'Polar Bear', 'Grizzly Bear', 3),
('Science', 'Which part of the plant conducts photosynthesis?', 'Stem', 'Roots', 'Leaves', 'Flowers', 3),
('Science', 'What is the most common blood type?', 'A', 'B', 'O', 'AB', 3),
('Science', 'Which gas is necessary for respiration?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 1),
('Science', 'Which part of the ear is responsible for balance?', 'Eardrum', 'Cochlea', 'Semicircular Canals', 'Hammer', 3),
('Science', 'Which planet is the hottest in our solar system?', 'Mercury', 'Venus', 'Mars', 'Jupiter', 2),
('Science', 'Which gas do humans exhale?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Helium', 2),
('Science', 'Which is the strongest muscle in the human body?', 'Biceps', 'Jaw Muscle (Masseter)', 'Quadriceps', 'Heart', 2),
('Science', 'What is the most common element in the Earth’s crust?', 'Oxygen', 'Silicon', 'Iron', 'Aluminum', 1),
('Science', 'What is the smallest planet in the Solar System?', 'Mercury', 'Mars', 'Venus', 'Pluto', 1),
('Science', 'What is the name of the nearest star to Earth?', 'Alpha Centauri', 'Proxima Centauri', 'Sirius', 'Betelgeuse', 2),
('Science', 'Which force keeps planets in orbit around the Sun?', 'Magnetism', 'Friction', 'Gravity', 'Inertia', 3),

-- Pop-Culture Questions
('Pop-Culture', 'Who directed the movie "Inception"?', 'Steven Spielberg', 'Christopher Nolan', 'James Cameron', 'Quentin Tarantino', 2),
('Pop-Culture', 'Which TV show featured a chemistry teacher-turned-drug dealer?', 'Breaking Bad', 'Dexter', 'Better Call Saul', 'The Wire', 1),
('Pop-Culture', 'Who was the first Disney princess?', 'Cinderella', 'Snow White', 'Aurora', 'Ariel', 2),
('Pop-Culture', 'Which movie franchise features a character named Jack Sparrow?', 'Pirates of the Caribbean', 'The Hobbit', 'Indiana Jones', 'James Bond', 1),
('Pop-Culture', 'Which video game series features the character Link?', 'The Legend of Zelda', 'Final Fantasy', 'Metroid', 'Super Mario', 1),
('Pop-Culture', 'Who is the lead singer of the band Queen?', 'Elton John', 'Mick Jagger', 'Freddie Mercury', 'David Bowie', 3),
('Pop-Culture', 'What is the name of the coffee shop in "Friends"?', 'Central Perk', 'Coffee House', 'Cafe 90', 'The Bean Spot', 1),
('Pop-Culture', 'Who played Iron Man in the Marvel Cinematic Universe?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo', 1),
('Pop-Culture', 'What year was the first iPhone released?', '2005', '2007', '2009', '2010', 2),
('Pop-Culture', 'Which artist released the album "Thriller"?', 'Prince', 'Michael Jackson', 'Madonna', 'Elton John', 2),
('Pop-Culture', 'Who created the animated series "The Simpsons"?', 'Seth MacFarlane', 'Matt Groening', 'Trey Parker', 'Mike Judge', 2),
('Pop-Culture', 'Which movie won the first-ever Academy Award for Best Picture?', 'Gone with the Wind', 'Wings', 'Casablanca', 'Citizen Kane', 2),
('Pop-Culture', 'Which social media platform was launched first?', 'Facebook', 'Twitter', 'Instagram', 'Snapchat', 1),
('Pop-Culture', 'What is the highest-grossing film of all time (not adjusted for inflation)?', 'Titanic', 'Avengers: Endgame', 'Avatar', 'Star Wars: The Force Awakens', 3),
('Pop-Culture', 'Who wrote the "Harry Potter" book series?', 'J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Suzanne Collins', 2),
('Pop-Culture', 'Which rapper is known for the album "The Marshall Mathers LP"?', 'Jay-Z', 'Dr. Dre', 'Eminem', 'Kanye West', 3),
('Pop-Culture', 'Which famous TV show features dragons and noble houses fighting for a throne?', 'The Witcher', 'House of Cards', 'Game of Thrones', 'The Mandalorian', 3),
('Pop-Culture', 'Who is known as the "Queen of Pop"?', 'Madonna', 'Beyoncé', 'Lady Gaga', 'Taylor Swift', 1),
('Pop-Culture', 'Which video game features a battle royale mode called Warzone?', 'Fortnite', 'PUBG', 'Call of Duty', 'Apex Legends', 3),
('Pop-Culture', 'Which 90s TV show featured the character Will Smith as a fictionalized version of himself?', 'Friends', 'Martin', 'The Fresh Prince of Bel-Air', 'Full House', 3),
('Pop-Culture', 'Which superhero is known as the "Dark Knight"?', 'Superman', 'Batman', 'Spider-Man', 'Iron Man', 2),
('Pop-Culture', 'Which artist had a hit song called "Blinding Lights"?', 'The Weeknd', 'Drake', 'Post Malone', 'Travis Scott', 1),
('Pop-Culture', 'What is the name of the villain in "The Lion King"?', 'Jafar', 'Scar', 'Hades', 'Gaston', 2),
('Pop-Culture', 'Who won the first season of "American Idol"?', 'Kelly Clarkson', 'Carrie Underwood', 'Fantasia Barrino', 'Ruben Studdard', 1),
('Pop-Culture', 'What does the acronym "GIF" stand for?', 'Graphics Interface Format', 'Graphics Interchange Format', 'Graphics Integrated File', 'Graphics Information Form', 2),
('Pop-Culture', 'Who played the lead role in "Forrest Gump"?', 'Tom Hanks', 'Leonardo DiCaprio', 'Matt Damon', 'Brad Pitt', 1),
('Pop-Culture', 'Which fast-food chain is famous for its "Big Mac"?', 'Burger King', 'McDonald’s', 'Wendy’s', 'KFC', 2),
('Pop-Culture', 'Which animated movie features the song "Let It Go"?', 'Moana', 'Frozen', 'Tangled', 'Encanto', 2),
('Pop-Culture', 'Who is known as the "King of Rock and Roll"?', 'Elvis Presley', 'Chuck Berry', 'Buddy Holly', 'Johnny Cash', 1),
('Pop-Culture', 'Which streaming platform produces "Stranger Things"?', 'Amazon Prime', 'HBO Max', 'Disney+', 'Netflix', 4),
('Pop-Culture', 'Which TV show featured the character Walter White?', 'Dexter', 'The Wire', 'Breaking Bad', 'Mad Men', 3),
('Pop-Culture', 'Which celebrity is known for the reality show "Keeping Up with the Kardashians"?', 'Paris Hilton', 'Kim Kardashian', 'Kylie Jenner', 'Khloé Kardashian', 2),
('Pop-Culture', 'Which Pixar movie features a character named Woody?', 'Finding Nemo', 'Up', 'Toy Story', 'The Incredibles', 3),
('Pop-Culture', 'Which pop star is known for hits like "Bad Guy" and "Happier Than Ever"?', 'Billie Eilish', 'Ariana Grande', 'Dua Lipa', 'Olivia Rodrigo', 1),
('Pop-Culture', 'What is the name of the wizarding school in "Harry Potter"?', 'Beauxbatons', 'Durmstrang', 'Hogwarts', 'Ilvermorny', 3),
('Pop-Culture', 'Which popular TV series is set in Hawkins, Indiana?', 'Dark', 'The Umbrella Academy', 'Stranger Things', 'The X-Files', 3),
('Pop-Culture', 'Who played Jack Dawson in "Titanic"?', 'Johnny Depp', 'Leonardo DiCaprio', 'Brad Pitt', 'Tom Cruise', 2),
('Pop-Culture', 'Which game features the phrase "The cake is a lie"?', 'Half-Life', 'Bioshock', 'Portal', 'Doom', 3),
('Pop-Culture', 'Which K-pop group released the song "Dynamite"?', 'Blackpink', 'BTS', 'EXO', 'TWICE', 2),
('Pop-Culture', 'Which famous horror author wrote "It" and "The Shining"?', 'Edgar Allan Poe', 'Stephen King', 'H.P. Lovecraft', 'Bram Stoker', 2),
('Pop-Culture', 'Which artist is famous for "Shape of You"?', 'Drake', 'Ed Sheeran', 'Shawn Mendes', 'Justin Bieber', 2),
('Pop-Culture', 'Which social media app is known for short videos?', 'Facebook', 'Twitter', 'TikTok', 'Reddit', 3),
('Pop-Culture', 'Which superhero is also known as the "Merc with a Mouth"?', 'Deadpool', 'Wolverine', 'Spider-Man', 'The Flash', 1),
('Pop-Culture', 'Which band released the song "Bohemian Rhapsody"?', 'The Rolling Stones', 'The Beatles', 'Queen', 'Pink Floyd', 3),
('Pop-Culture', 'What is the name of the main character in "The Legend of Zelda"?', 'Zelda', 'Ganon', 'Link', 'Epona', 3),
('Pop-Culture', 'Who voices Woody in the "Toy Story" movies?', 'Tom Hanks', 'Tim Allen', 'Robin Williams', 'Chris Evans', 1),
('Pop-Culture', 'Which show features the characters Sheldon, Leonard, and Penny?', 'Friends', 'The Big Bang Theory', 'How I Met Your Mother', 'Brooklyn Nine-Nine', 2),
('Pop-Culture', 'What is the name of Batman’s butler?', 'Alfred', 'Jeeves', 'Jarvis', 'Henry', 1),
('Pop-Culture', 'Which animated TV show features characters named Finn and Jake?', 'Adventure Time', 'Rick and Morty', 'The Simpsons', 'Family Guy', 1),
('Pop-Culture', 'Which superhero movie features the character Erik Killmonger?', 'Black Panther', 'Spider-Man: No Way Home', 'The Dark Knight', 'Iron Man', 1),


-- Wild Questions
('Wild', 'Which fruit contains the most water?', 'Apple', 'Strawberry', 'Watermelon', 'Banana', 3),
('Wild', 'What is the only even prime number?', '2', '4', '6', '8', 1),
('Wild', 'What is the national animal of Scotland?', 'Unicorn', 'Lion', 'Dragon', 'Eagle', 1),
('Wild', 'Which famous scientist had a pet parrot that would curse?', 'Albert Einstein', 'Nikola Tesla', 'Isaac Newton', 'Charles Darwin', 2),
('Wild', 'Which country has the most time zones?', 'Russia', 'United States', 'France', 'China', 3),
('Wild', 'What is the rarest M&M color?', 'Brown', 'Red', 'Green', 'Blue', 1),
('Wild', 'How long does it take sunlight to reach Earth?', '8 minutes', '12 minutes', '5 minutes', '20 minutes', 1),
('Wild', 'Which country has the longest name?', 'United Kingdom', 'Democratic Republic of the Congo', 'United States of America', 'Liechtenstein', 2),
('Wild', 'Which letter is worth the most points in Scrabble?', 'X', 'Z', 'Q', 'J', 3),
('Wild', 'What was the first toy to be advertised on television?', 'Lego', 'Slinky', 'Mr. Potato Head', 'Barbie', 3),
('Wild', 'Which U.S. state has a one-word name that ends in "K"?', 'Alaska', 'New York', 'Hawaii', 'Arkansas', 1),
('Wild', 'Which fast-food chain once offered a "Left-Handed Whopper"?', 'McDonald’s', 'Burger King', 'Wendy’s', 'KFC', 2),
('Wild', 'What is the most common letter in the English language?', 'A', 'E', 'R', 'S', 2),
('Wild', 'Which playing card is known as "The Death Card"?', 'Ace of Spades', 'King of Hearts', 'Joker', 'Queen of Diamonds', 1),
('Wild', 'What does the "E" in Chuck E. Cheese stand for?', 'Entertainment', 'Edward', 'Ethan', 'Elephant', 1),
('Wild', 'Which common condiment was sold as medicine in the 1800s?', 'Mustard', 'Ketchup', 'Soy Sauce', 'Mayonnaise', 2),
('Wild', 'Which ancient civilization invented the first written language?', 'Romans', 'Sumerians', 'Egyptians', 'Greeks', 2),
('Wild', 'What was the first product to have a barcode scanned?', 'Coca-Cola', 'A pack of gum', 'A box of cereal', 'A candy bar', 2),
('Wild', 'Which planet has the most moons?', 'Mars', 'Saturn', 'Jupiter', 'Neptune', 2),
('Wild', 'What does the term "piano" mean in music?', 'Loud', 'Soft', 'Fast', 'Slow', 2),
('Wild', 'What was the first U.S. state?', 'New York', 'Massachusetts', 'Delaware', 'Virginia', 3),
('Wild', 'Which fictional detective lived at 221B Baker Street?', 'Hercule Poirot', 'Sherlock Holmes', 'Miss Marple', 'Philip Marlowe', 2),
('Wild', 'Which country drinks the most coffee per capita?', 'USA', 'Finland', 'Italy', 'Brazil', 2),
('Wild', 'Which fast-food chain was founded first?', 'Burger King', 'McDonald’s', 'KFC', 'Subway', 3),
('Wild', 'What is the fear of long words called?', 'Claustrophobia', 'Hippopotomonstrosesquipedaliophobia', 'Acrophobia', 'Arachnophobia', 2),
('Wild', 'What was the first message sent over the Internet?', 'Hello, World!', 'Login Successful', 'LO', 'TEST', 3),
('Wild', 'Which animal can sleep for up to three years?', 'Bear', 'Frog', 'Snail', 'Tortoise', 3),
('Wild', 'Which U.S. president appears on the $2 bill?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin', 3),
('Wild', 'What year did the Titanic sink?', '1905', '1912', '1920', '1898', 2),
('Wild', 'Which Olympic sport involves fencing, swimming, equestrian, shooting, and running?', 'Decathlon', 'Triathlon', 'Pentathlon', 'Heptathlon', 3),
('Wild', 'Who was the first man in space?', 'Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn', 3),
('Wild', 'What is the only continent without native reptiles?', 'Europe', 'North America', 'Antarctica', 'Asia', 3),
('Wild', 'Which U.S. state has the most national parks?', 'California', 'Alaska', 'Colorado', 'Arizona', 1),
('Wild', 'What is the most spoken language in the world?', 'English', 'Spanish', 'Mandarin', 'Hindi', 3),
('Wild', 'What is the only country with a flag that is not rectangular?', 'Switzerland', 'Nepal', 'Bhutan', 'Vatican City', 2),
('Wild', 'What is the heaviest naturally occurring element?', 'Iron', 'Gold', 'Uranium', 'Plutonium', 3),
('Wild', 'Which classic novel begins with "Call me Ishmael"?', 'Moby Dick', 'Dracula', 'The Great Gatsby', 'Frankenstein', 1),
('Wild', 'Which U.S. president appears on the $50 bill?', 'Thomas Jefferson', 'Ulysses S. Grant', 'Benjamin Franklin', 'Andrew Jackson', 2),
('Wild', 'What is the only U.S. state with a one-syllable name?', 'Maine', 'Texas', 'Ohio', 'Idaho', 1),
('Wild', 'Which European country is famous for its windmills and tulips?', 'Germany', 'Netherlands', 'Denmark', 'France', 2),
('Wild', 'Which artist painted the ceiling of the Sistine Chapel?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello', 2),
('Wild', 'What was the first video game ever created?', 'Pac-Man', 'Pong', 'Tennis for Two', 'Space Invaders', 3),
('Wild', 'Which fruit does the word "pineapple" originally come from?', 'Banana', 'Apple', 'Mango', 'Pinecone', 4),
('Wild', 'Which country is home to the Eiffel Tower?', 'Germany', 'France', 'Spain', 'Italy', 2),
('Wild', 'What is the only U.S. state that grows coffee?', 'Hawaii', 'California', 'Florida', 'Texas', 1),
('Wild', 'Which color is associated with royalty?', 'Green', 'Purple', 'Red', 'Blue', 2),
('Wild', 'What is the only continent with no permanent human population?', 'Antarctica', 'Asia', 'Europe', 'Australia', 1),
('Wild', 'Which planet has the longest rotation period?', 'Mercury', 'Venus', 'Mars', 'Neptune', 2),
('Wild', 'What is the most expensive spice by weight?', 'Vanilla', 'Saffron', 'Cinnamon', 'Cardamom', 2),
('Wild', 'Which natural phenomenon is measured using the Richter scale?', 'Hurricanes', 'Tornadoes', 'Earthquakes', 'Tsunamis', 3);